name: Generate changelog
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
      - name: Generate changelog
        uses: pgmarc/Pricing-Intelligence-Interpretation-Process/.github/actions/sphere-changelog@358d1ac5ead33784b1f7a6281689ed9161828e2b
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
